name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the 0th min
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in syntackle posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "fetched and updated readme with latest blog posts"
          feed_list: "https://syntackle.live/feed.xml"
          max_post_count: 5
          date_format: "mmm d, yyyy"
          template: <p align='center'>• <a href='$url'>$title</a> - $date</p>